### ISSUE TITLE
Define pattern under `unit module` in `.recink.yml`

### ISSUE THREAD

**Issue by avozicov** [TerraHubCorp/terrahub#10]
I wanted to request a feature for `recink unit` component so I will try to describe it here for further discussion:

- Add a possibility to define `unit test pattern` under `module configuration` in `.recink.yml` 

For example:
- this is the global unit component config:
```
test:
    mocha:
      options:                                                
        ui: 'bdd'
        reporter: 'spec'
    pattern:                                                 
      - /.+\.spec\.js$/i  
      # - account/retrieve.spec.js
```
 
- those are two `unit test related modules` with different scripts but they are matched by the same `spec` pattern:
```
unit:  
  root: './quality-assurance/tests/unit/'

api-test:
  root: './terrahub-api/src/tests/functional/'
```

Would be great to have something like this so I can define different patterns under each modules:
```
unit:  
  root: './quality-assurance/tests/unit/'
  pattern:                                                 
      - /.+\.spec\.js$/i  

api-test:
  root: './terrahub-api/src/tests/functional/'
  pattern:                                                   
      - account/retrieve.spec.js
```

If it is a valid use case the same can be applied for `e2e component` ;)
