### ISSUE TITLE
Configure backendConfig and cloudConfig (similar to backendAccount and cloudAccount)

### ISSUE THREAD

**Issue by eistrati** [TerraHubCorp/terrahub#1016]
### `backendConfig` ==> `backendAccount` ??
```yaml
  backendAccount: cloudready
  backendConfig:
    backendKEY: backendVALUE
    ### ==> `terraform init -input=false -backend-config="role_arn=arn:aws:iam::123456789012:role/pipeline-role"`
```

### `cloudConfig` ==> `cloudAccount` ??
```yaml
  cloudAccount: cloudready
  cloudConfig:
    default:
      region: us-east-1
      # aws_access_key_id: VALUE1
      # aws_secret_access_key: VALUE2
      # aws_session_token: VALUE3
    terrahub:
      role_arn: arn:aws:iam::123456789012:role/pipeline-role
      source_profile: default
```

## Configure ENV variables in Project
```yaml
project:
  env:
    variables:
      AWS_DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID: VALUE1
      AWS_SECRET_ACCESS_KEY: VALUE2
      AWS_SESSION_TOKEN: VALUE3
```

## Configure ENV variables in Component
```yaml
component:
  env:
    variables:
      AWS_DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID: VALUE1
      AWS_SECRET_ACCESS_KEY: VALUE2
      AWS_SESSION_TOKEN: VALUE3
```
