### ISSUE TITLE
How to replace recink run cnci

### ISSUE THREAD

**Issue by ddimitrioglo** [TerraHubCorp/terrahub#110]
* Do we need it as part of terrahub?
* How should we implement this?

**Comment by eistrati** [comment]
@ddimitrioglo Proposed config structure:

```
terrahub:
  parameter-store:
    THUB_TOKEN: "/CodeBuild/TerraHubCorp/terrahub/THUB_TOKEN"
  preprocess:
    'terrahub.token': 'eval'
    'terrahub.ci.options.user': 'eval'
    'terrahub.ci.options.token': 'eval'
    'terrahub.ci.options.jobName': 'eval'
    'terrahub.ci.options.buildNumber': 'eval'
  token: 'process.env.THUB_TOKEN'
  ci:
    provider: jenkins
    options:
      user: 'process.env.JENKINS_USER'
      token: 'process.env.JENKINS_TOKEN'
      jobName: 'process.env.JOB_NAME'
      buildNumber: 'process.env.BUILD_NUMBER'
```
