### ISSUE TITLE
Wrong behavior for `thub project -name` command 

### ISSUE THREAD

**Issue by avozicov** [TerraHubCorp/terrahub#170]
When `thub project -name` command is provided with empty name option the project name in `.terrahub.yml` is defined as  `true` which is wrong 
<img width="501" alt="screen shot 2018-07-23 at 18 28 56" src="https://user-images.githubusercontent.com/12330493/43086552-4d6d81a4-8ea6-11e8-8873-7b0d6b5acfd0.png">

```
project:
  name: 'true'
  code: '06a32f4d'
  provider: 'aws'

terraform:
  varFile:
    - 'default.tfvars'
```
