### ISSUE TITLE
Multiple dependencies between terrahub components

### ISSUE THREAD

**Issue by eistrati** [TerraHubCorp/terrahub#177]
Currently, one dependency per terrahub component is NOT enough:

```
name: 'my-terrahub-component'
parent: '../my-other-terrahub-component/'
```

Let's implement the new multiple dependencies approach using like this:
```
component:
  name: 'my-terrahub-component'
  depends_on:
    - '../my-other-terrahub-component1/'
    - '../my-other-terrahub-component2/'
    [...]
    - '../my-other-terrahub-componentN/'
```

Here is a link to help with "optimized task scheduling with dependencies": https://stackoverflow.com/questions/18314250/optimized-algorithm-to-schedule-tasks-with-dependency
