### ISSUE TITLE
Mapping capability in both root config and local config

### ISSUE THREAD

**Issue by eistrati** [TerraHubCorp/terrahub#281]
## Describe the Feature

Add mapping capability in both [root config](https://github.com/TerraHubCorp/terrahub/blob/master/src/templates/config/project/.terrahub.yml.twig) and [local config](https://github.com/TerraHubCorp/terrahub/blob/master/src/templates/config/component/.terrahub.yml.twig) to help continuous integration service to optimize the number of executed terrahub components to the minimum.

Here below is proposed syntax for YAML format:
```yaml
ci:
  mapping:
    - '.' ## current folder relative to where .terrahub.yml is defined
    - '..' ## parent folder relative to where .terrahub.yml is defined
    - 'path/to/some/other/folder/or/file'
```

## Expected Behavior

When webhook associated to git commit or pull request is triggered, terrahub api will receive a list of updated files that will be matched to mapping configs from .terrahub.yml files. Matching results will provide an optimized (smaller) list of terrahub components that will be executed by continuous integration service.

In case there are no matches or there is no mapping defined, this feature will be practically ignored and ALL terrahub components will be executed.
