### ISSUE TITLE
Worker error: "it.split is not a function"

### ISSUE THREAD

**Issue by eistrati** [TerraHubCorp/terrahub#282]
## Describe the Bug

```
$ thub build -i lambda_job_create
[lambda_job_create] BUILD: Skipping pre_build step
[lambda_job_create] BUILD: pre_build step successful
❌ Worker error: "it.split is not a function"
```

## Steps to Reproduce

1. Configure .terrahub.yml similar to below:
```yaml
build:
  phases:
    build:
      commands:
        - 'echo "BUILD: Running build step"'
        - 'node lib/lambda-compile/index.js src/backend/job/create .terrahub/lambda_job_create s3://[REDACTED] nodejs8.10.zip'
      finally:
        - 'echo "BUILD: build step successful"'

```
2. `terrahub build` is executed successfully
3. Remove single quotes from each command:
```yaml
build:
  phases:
    build:
      commands:
        - echo "BUILD: Running build step"
        - node lib/lambda-compile/index.js src/backend/job/create .terrahub/lambda_job_create s3://[REDACTED] nodejs8.10.zip
      finally:
        - echo "BUILD: build step successful"

```
4. `terrahub build` returns worker error
