### ISSUE TITLE
Path must be relative to .terrahub.yml when executing `terrahub build`

### ISSUE THREAD

**Issue by eistrati** [TerraHubCorp/terrahub#283]
## Describe the Feature

Currently, the path of scripts defined in .terrahub.yml is relative to where I'm triggering the execution of `terrahub build`. For example, let's take the following real example:
```yaml
build:
  phases:
    build:
      commands:
        - echo "BUILD: Running build step"
        - node lib/lambda-compile/index.js src/backend/job/create .terrahub/lambda_job_create s3://[REDACTED] nodejs8.10.zip
      finally:
        - echo "BUILD: build step successful"
```

If I execute `terrahub build` from project's root, it works fine. BUT if I execute the same command from anywhere else, it fails.

## Expected Behavior

I would like to be able to run `terrahub build` from anywhere. Therefore I propose to define the path related to .terrahub.yml file.
