### ISSUE TITLE
Wrong config file is created when running `terrahub component` for already existed terraform component

### ISSUE THREAD

**Issue by avozicov** [TerraHubCorp/terrahub#446]
## Steps to Reproduce
1. Create terraform component and `cd` to component dir
2. Run the command 'terrahub component -n [component_name]'

BUG:
The following not valid config is created 
```yaml
component:
   name: [name]
   dependsOn: []
```

## Expected Behavior

```yaml
## local config
component:
  name: 'one'
  mapping:
    - '.'
```
