### ISSUE TITLE
Implement TerraHub CLI feature that uses cloud accounts and continuous delivery accounts from TerraHub API

### ISSUE THREAD

**Issue by eistrati** [TerraHubCorp/terrahub#478]
## Describe the Feature

Implement TerraHub CLI feature that uses cloud accounts and continuous delivery accounts from TerraHub API

## Expected Behavior

Let's match git remote origin URL with corresponding code repository that is saved in TerraHub API and allow developers / `.terrahub.yml` file to specify which credentials / accounts they want to use for specific terrahub project or particular terrahub component

**Comment by eistrati** [comment]
Allow the following syntax:
```
terraform:
  cloudAccount: mitocgroup
  varFile:
    - s3://[bucket_name]/[path_to]/default.tfvars
```
