### ISSUE TITLE
Add `mapping: ['.']` to be default in terrahub cli

### ISSUE THREAD

**Issue by avozicov** [TerraHubCorp/terrahub#546]
- This is required to avoid specifying in every .terrahub.yml and save some space

**Comment by ddimitrioglo** [comment]
Note: this is implemented **only** for JIT implementation

**Comment by avozicov** [comment]
Implemented 
```
Alexandrs-MacBook-Pro:aws_s3_bucket alexandrvozicov$ cat .terrahub.yml 
## local config
component:
  name: 'aws_s3_bucket'
  mapping:
    - '.'
  template:
    # terraform:
    #   backend:
    #     s3:
    #       region: 'us-east-1'
    #       bucket: 'bucket-name'
    #       key: 'path/to/terraform.tfstate'
    # data:
    #   aws_s3_bucket_object:
    #     aws_s3_bucket_object:
    #       key: 'index.txt'
    #       bucket: '${aws_s3_bucket.aws_s3_bucket.id}'
    resource:
```
