### ISSUE TITLE
Generate variable.tf based on tfvars config when variable config is missing and template is enabled

### ISSUE THREAD

**Issue by eistrati** [TerraHubCorp/terrahub#551]
This feature will reduce our config size.

Right now it looks like this:

```
    variable:
      remote_state_key:
        type: 'string'
      aliases:
        type: 'list'
      comment:
        type: 'string'
      origin_id:
        type: 'string'
      origin_name:
        type: 'string'
    tfvars:
      remote_state_key: 'terraform/terrahub/s3_bucket/terraform.tfstate'
      aliases: ['www.terrahub.io']
      comment: 'www.terrahub.io'
      origin_id: 's3-website-www.terrahub.io.s3-website-us-east-1.amazonaws.com'
      origin_name: 'www.terrahub.io.s3-website-us-east-1.amazonaws.com'
```

After we implement this feature, it should look like this (and provide the same functionality as above):

```
    tfvars:
      remote_state_key: 'terraform/terrahub/s3_bucket/terraform.tfstate'
      aliases: ['www.terrahub.io']
      comment: 'www.terrahub.io'
      origin_id: 's3-website-www.terrahub.io.s3-website-us-east-1.amazonaws.com'
      origin_name: 'www.terrahub.io.s3-website-us-east-1.amazonaws.com'
```

**Comment by avozicov** [comment]
1. A. Test Passed with the variables config:

```
## local config
component:
  name: test-terrahub-component
  template:
    resource:
      aws_ssm_parameter:
        test-terrahub-component:
          name: '${var.test-terrahub-component_name}'
          value: '${var.test-terrahub-component_value}'
          type: '${var.test-terrahub-component_type}'
    variable:
      test-terrahub-component_name:
        type: 'string'
      test-terrahub-component_value:
        type: 'string'
      test-terrahub-component_type:
        type: 'string'
    output:
      id:
        value: '${aws_ssm_parameter.test-terrahub-component.id}'
      thub_id:
        value: '${aws_ssm_parameter.test-terrahub-component.id}'
      arn:
        value: '${aws_ssm_parameter.test-terrahub-component.arn}'
      key_id:
        value: '${aws_ssm_parameter.test-terrahub-component.key_id}'
    tfvars:
      test-terrahub-component_name: test-terrahub-component_name
      test-terrahub-component_value: test-terrahub-component_value
      test-terrahub-component_type: String
```
output:
```
[test-terrahub-component] Terraform will perform the following actions:
[test-terrahub-component] 
[test-terrahub-component] + aws_ssm_parameter.test-terrahub-component
      id:     <computed>
[test-terrahub-component]       arn:    <computed>
[test-terrahub-component]       key_id: <computed>
[test-terrahub-component]       name:   "test-terrahub-component_name"
[test-terrahub-component]       type:   "String"
[test-terrahub-component]       value:  <sensitive>
[test-terrahub-component] Plan: 1 to add, 0 to change, 0 to destroy.
[test-terrahub-component] 
[test-terrahub-component] ------------------------------------------------------------------------
[test-terrahub-component] 
[test-terrahub-component] This plan was saved to: /Users/alexandrvozicov/.terrahub/cache/jit/test-terrahub-component_7f2a6dcd/terraform.tfplan

[test-terrahub-component] To perform exactly these actions, run the following command to apply:
[test-terrahub-component]     terraform apply "/Users/alexandrvozicov/.terrahub/cache/jit/test-terrahub-component_7f2a6dcd/terraform.tfplan"
[test-terrahub-component] 
✅ Done
```

1. B.  Test Passed when removed `variables` config block from component .yml 
```
## local config
component:
  name: test-terrahub-component
  template:
    resource:
      aws_ssm_parameter:
        test-terrahub-component:
          name: '${var.test-terrahub-component_name}'
          value: '${var.test-terrahub-component_value}'
          type: '${var.test-terrahub-component_type}'
    output:
      id:
        value: '${aws_ssm_parameter.test-terrahub-component.id}'
      thub_id:
        value: '${aws_ssm_parameter.test-terrahub-component.id}'
      arn:
        value: '${aws_ssm_parameter.test-terrahub-component.arn}'
      key_id:
        value: '${aws_ssm_parameter.test-terrahub-component.key_id}'
    tfvars:
      test-terrahub-component_name: test-terrahub-component_name
      test-terrahub-component_value: test-terrahub-component_value
      test-terrahub-component_type: String
```
output:
```
[test-terrahub-component] Terraform will perform the following actions:

[test-terrahub-component] + aws_ssm_parameter.test-terrahub-component
[test-terrahub-component]       id:     <computed>
[test-terrahub-component]       arn:    <computed>
[test-terrahub-component]       key_id: <computed>
[test-terrahub-component]       name:   "test-terrahub-component_name"
[test-terrahub-component]       type:   "String"
[test-terrahub-component]       value:  <sensitive>
[test-terrahub-component] Plan: 1 to add, 0 to change, 0 to destroy.

[test-terrahub-component] ------------------------------------------------------------------------
[test-terrahub-component] 
[test-terrahub-component] This plan was saved to: /Users/alexandrvozicov/.terrahub/cache/jit/test-terrahub-component_7f2a6dcd/terraform.tfplan

[test-terrahub-component] To perform exactly these actions, run the following command to apply:
[test-terrahub-component]     terraform apply "/Users/alexandrvozicov/.terrahub/cache/jit/test-terrahub-component_7f2a6dcd/terraform.tfplan"

✅ Done
Alexandrs-MacBook-Pro:test alexandrvozicov$ 
```

1. C. Test Passed when removed .tfvars config from component .yml
```
## local config
component:
  name: test-terrahub-component
  template:
    resource:
      aws_ssm_parameter:
        test-terrahub-component:
          name: '${var.test-terrahub-component_name}'
          value: '${var.test-terrahub-component_value}'
          type: '${var.test-terrahub-component_type}'
    output:
      id:
        value: '${aws_ssm_parameter.test-terrahub-component.id}'
      thub_id:
        value: '${aws_ssm_parameter.test-terrahub-component.id}'
      arn:
        value: '${aws_ssm_parameter.test-terrahub-component.arn}'
      key_id:
        value: '${aws_ssm_parameter.test-terrahub-component.key_id}'
```
output:
```
 └─ test-terrahub-component
💡 'terrahub run' action is executed for above list of components.
💡 [test-terrahub-component] terraform init -no-color -force-copy -input=false .
❌ [test-terrahub-component] 

❌ [test-terrahub-component] Error: resource 'aws_ssm_parameter.test-terrahub-component' config: unknown variable referenced: 'test-terrahub-component_name'; define it with a 'variable' block
❌ [test-terrahub-component] Error: resource 'aws_ssm_parameter.test-terrahub-component' config: unknown variable referenced: 'test-terrahub-component_value'; define it with a 'variable' block
❌ [test-terrahub-component] Error: resource 'aws_ssm_parameter.test-terrahub-component' config: unknown variable referenced: 'test-terrahub-component_type'; define it with a 'variable' block
❌ [test-terrahub-component] 
❌ Worker error: "\nError: resource 'aws_ssm_parameter.test-terrahub-component' config: unknown variable referenced: 'test-terrahub-component_name'; define it with a 'variable' block\n\n\n\nError: resource 'aws_ssm_parameter.test-terrahub-component' config: unknown variable referenced: 'test-terrahub-component_value'; define it with a 'variable' block\n\n\n\nError: resource 'aws_ssm_parameter.test-terrahub-component' config: unknown variable referenced: 'test-terrahub-component_type'; define it with a 'variable' block\n\n\n"
Alexandrs-MacBook-Pro:test alexandrvozicov$ 
```
