### ISSUE TITLE
Copy all files and folders when template is enabled

### ISSUE THREAD

**Issue by eistrati** [TerraHubCorp/terrahub#552]
We currently have `./scripts` and `./iam_policy` in `s3_bucket` component. When using `template`, generated terraform in `~/.terrahub/cache/jit/` doesn't include these 2 folders. Please copy them and make sure they are available next to generated terraform files.

**Comment by eistrati** [comment]
On the same topic, please expose `component` config from .terrahub.yml as `local.component` (except `template`). Example use case:

BEFORE
```
component:
  template:
    data:
      external:
        s3_bucket:
          depends_on: ['aws_s3_bucket.s3_bucket']
          program: ['node', '${local.project["path"]}/.terrahub/s3_bucket/scripts/build.js']
          query:
            env: '${terraform.workspace}'
            component: 's3_bucket'
[...]
```

AFTER
```
component:
  template:
    data:
      external:
        s3_bucket:
          depends_on: ['aws_s3_bucket.s3_bucket']
          program: ['node', '${local.component["path"]}/scripts/build.js']
          query:
            env: '${terraform.workspace}'
            component: 's3_bucket'
[...]
```
