### ISSUE TITLE
Process template config to update relative paths to reference / start with project root path

### ISSUE THREAD

**Issue by eistrati** [TerraHubCorp/terrahub#564]
# Feature Report

## Describe the Feature

Process template config to update relative paths to reference / start with project root path

## Expected Behavior

For example: `template.module.*.source`
```
## local config
component:
  name: 's3_bucket'
  template:
    module:
      iam_policy_module:
        source: '../iam_policy'
        account_id: '${local.account_id}'
        region: '${local.region}'
        s3_bucket_name: '${var.s3_bucket_name}'
```

When JIT generates .tf files from .yml config, relative path of current module should be transformed to path (to be discussed: relative or absolute?) pointed to project root path.

For example:
`source: '../iam_policy'`
will become
`source: '/home/user/projects/security_terraform/roles/iam_policy'`

**Comment by avozicov** [comment]
Implemented.
- Requires to be released in alpha

Test Script:
call module component .terrahub.yml:
```
## local config
component:
  name: terrahub-component-call-module
  template:
      module:
        terrahub-project:
          source: '../../terrahub-project/terrahub-component'
          terrahub-component_name: terrahub-component_name
          terrahub-component_value: terrahub-component_value
          terrahub-component_type: String 
``` 
Output for terrahub run: 

```
Alexandrs-MacBook-Pro:terrahub-component-call-module alexandrvozicov$ terrahub run
Project: terrahub-project
 └─ terrahub-component-call-module
💡 'terrahub run' action is executed for above list of components.
💡 [terrahub-component-call-module] terraform init -no-color -force-copy -input=false .
[terrahub-component-call-module] Initializing modules...
[terrahub-component-call-module] - module.terrahub-project
[terrahub-component-call-module] 
[terrahub-component-call-module] Initializing provider plugins...
[terrahub-component-call-module] 
[terrahub-component-call-module] The following providers do not have any version constraints in configuration,
[terrahub-component-call-module] so the latest version was installed.

[terrahub-component-call-module] To prevent automatic upgrades to new major versions that may contain breaking
[terrahub-component-call-module] changes, it is recommended to add version = "..." constraints to the
[terrahub-component-call-module] corresponding provider blocks in configuration, with the constraint strings
[terrahub-component-call-module] suggested below.

[terrahub-component-call-module] * provider.aws: version = "~> 2.11"

[terrahub-component-call-module] Terraform has been successfully initialized!
[terrahub-component-call-module] 
[terrahub-component-call-module] You may now begin working with Terraform. Try running "terraform plan" to see
[terrahub-component-call-module] any changes that are required for your infrastructure. All Terraform commands
[terrahub-component-call-module] should now work.

[terrahub-component-call-module] If you ever set or change modules or backend configuration for Terraform,
[terrahub-component-call-module] rerun this command to reinitialize your working directory. If you forget, other
[terrahub-component-call-module] commands will detect it and remind you to do so if necessary.
💡 [terrahub-component-call-module] terraform workspace list
[terrahub-component-call-module] * default

💡 [terrahub-component-call-module] terraform plan -no-color -var='region=us-east-1' -out=/Users/alexandrvozicov/.terrahub/cache/jit/terrahub-component-call-module_0ecd9877/terraform.tfplan -input=false
[terrahub-component-call-module] Refreshing Terraform state in-memory prior to plan...
[terrahub-component-call-module] The refreshed state will be used to calculate this plan, but will not be
[terrahub-component-call-module] persisted to local or remote state storage.

[terrahub-component-call-module] 
[terrahub-component-call-module] ------------------------------------------------------------------------
[terrahub-component-call-module] 
[terrahub-component-call-module] An execution plan has been generated and is shown below.
[terrahub-component-call-module] Resource actions are indicated with the following symbols:
  + create
[terrahub-component-call-module] 
[terrahub-component-call-module] Terraform will perform the following actions:
[terrahub-component-call-module] 
[terrahub-component-call-module] + module.terrahub-project.aws_ssm_parameter.terrahub-component
[terrahub-component-call-module]       id:     <computed>
      arn:    <computed>
      key_id: <computed>
      name:   "terrahub-component_name"
[terrahub-component-call-module]       tier:   "Standard"
[terrahub-component-call-module]       type:   "String"
[terrahub-component-call-module]       value:  <sensitive>
[terrahub-component-call-module] Plan: 1 to add, 0 to change, 0 to destroy.
[terrahub-component-call-module] 
[terrahub-component-call-module] ------------------------------------------------------------------------
[terrahub-component-call-module] 
[terrahub-component-call-module] This plan was saved to: /Users/alexandrvozicov/.terrahub/cache/jit/terrahub-component-call-module_0ecd9877/terraform.tfplan

[terrahub-component-call-module] To perform exactly these actions, run the following command to apply:
[terrahub-component-call-module]     terraform apply "/Users/alexandrvozicov/.terrahub/cache/jit/terrahub-component-call-module_0ecd9877/terraform.tfplan"
[terrahub-component-call-module] 
✅ Done
```

cat module.tf: 
```
Alexandrs-MacBook-Pro:terrahub-component-call-module alexandrvozicov$ cat ~/.terrahub/cache/jit/terrahub-component-call-module_0ecd9877/module.tf 
{
  "module": {
    "terrahub-project": {
      "source": "/Users/alexandrvozicov/Projects/scripts/automation/terrahub-project/terrahub-component",
      "terrahub-component_name": "terrahub-component_name",
      "terrahub-component_value": "terrahub-component_value",
      "terrahub-component_type": "String"
    }
  }
}
Alexandrs-MacBook-Pro:terrahub-component-call-module alexandrvozicov$ 
```
