### ISSUE TITLE
Default mapping to current folder doesn't work

### ISSUE THREAD

**Issue by eistrati** [TerraHubCorp/terrahub#640]
# Bug Report
Default mapping to current folder doesn't work

## Describe the Bug
Default mapping to current folder doesn't work.
1. Here below is an example of failed job: https://github.com/TerraHubCorp/demo-terraform-automation-gcp/pull/24#issuecomment-475993565
2. Here below is an example of successful job after adding `mapping: [.]` into component's configuration: https://github.com/TerraHubCorp/demo-terraform-automation-gcp/pull/24#issuecomment-475994953

**Comment by avozicov** [comment]
Fixed and merged up to `dev`.

lambda .terrahub.yml default mapping:

```
component:
  name: lambda
  dependsOn:
    - ../iam_role
    - ../security_group
    - ../subnet_private
  template:
    resource:
   ...
```

output:
```
Alexandrs-MacBook-Pro:demo-terraform-automation-aws alexandrvozicov$ curl https://oo2bhftiek.execute-api.us-east-1.amazonaws.com/demo
{"statusCode":200,"body":"\"Hello from Lambda!\""}Alexandrs-MacBook-Pro:demo-terraform-automation-aws alexandrvozicov$ 
```
