### ISSUE TITLE
Add capability to store remote tfvars in google storage

### ISSUE THREAD

**Issue by eistrati** [TerraHubCorp/terrahub#691]
# Feature Report
Add capability to store remote tfvars in google storage

## Describe the Feature

Currently, we are able to store tfvars in S3:
```
terraform:
  cloudAccount: mitocgroup_on_aws
  varFile:
    - s3://[bucket_name]/[path_to]/default.tfvars
```

Please add the same feature for GS:
```
terraform:
  cloudAccount: mitocgroup_on_gcp
  varFile:
    - gs://[bucket_name]/[path_to]/default.tfvars
```

**Comment by avozicov** [comment]
Implemented.
- requires to be released in alpha 

gcp:
```
## local config
component:
  name: terrahub-component-call-module
  template:
      module:
        terrahub-project:
          source: '../../terrahub-project/terrahub-component'
          terrahub-component_name: ${var.terrahub-component_name}
          terrahub-component_value: terrahub-component_value
          terrahub-component_type: String
terraform:
  varFile: 
    - gs://bucket-691/default.tfvars 
```

Output:
```
Alexandrs-MacBook-Pro:terrahub-component-call-module alexandrvozicov$ rm -rf ~/.terrahub/cache/*
Alexandrs-MacBook-Pro:terrahub-component-call-module alexandrvozicov$ terrahub run
Project: terrahub-project
 └─ terrahub-component-call-module
💡 'terrahub run' action is executed for above list of components.
💡 [terrahub-component-call-module] terraform init -no-color -force-copy -input=false .
[terrahub-component-call-module] Initializing modules...
[terrahub-component-call-module] - module.terrahub-project
[terrahub-component-call-module]   Getting source "/Users/alexandrvozicov/Projects/scripts/automation/terrahub-project/terrahub-component"
[terrahub-component-call-module] 
[terrahub-component-call-module] Initializing provider plugins...
[terrahub-component-call-module] - Checking for available provider plugins on https://releases.hashicorp.com...
[terrahub-component-call-module] - Downloading plugin for provider "aws" (2.11.0)...
[terrahub-component-call-module] 
[terrahub-component-call-module] The following providers do not have any version constraints in configuration,
so the latest version was installed.

To prevent automatic upgrades to new major versions that may contain breaking
[terrahub-component-call-module] changes, it is recommended to add version = "..." constraints to the
[terrahub-component-call-module] corresponding provider blocks in configuration, with the constraint strings
[terrahub-component-call-module] suggested below.

[terrahub-component-call-module] * provider.aws: version = "~> 2.11"

[terrahub-component-call-module] Terraform has been successfully initialized!
[terrahub-component-call-module] 
[terrahub-component-call-module] You may now begin working with Terraform. Try running "terraform plan" to see
[terrahub-component-call-module] any changes that are required for your infrastructure. All Terraform commands
[terrahub-component-call-module] should now work.

[terrahub-component-call-module] If you ever set or change modules or backend configuration for Terraform,
[terrahub-component-call-module] rerun this command to reinitialize your working directory. If you forget, other
[terrahub-component-call-module] commands will detect it and remind you to do so if necessary.
💡 [terrahub-component-call-module] terraform workspace list
[terrahub-component-call-module] * default

💡 [terrahub-component-call-module] terraform plan -no-color -var-file='/Users/alexandrvozicov/.terrahub/cache/jit/terrahub-component-call-module_0ecd9877/default.tfvars' -out=/Users/alexandrvozicov/.terrahub/cache/jit/terrahub-component-call-module_0ecd9877/terraform.tfplan -input=false
[terrahub-component-call-module] Refreshing Terraform state in-memory prior to plan...
[terrahub-component-call-module] The refreshed state will be used to calculate this plan, but will not be
[terrahub-component-call-module] persisted to local or remote state storage.

[terrahub-component-call-module] 
[terrahub-component-call-module] ------------------------------------------------------------------------
[terrahub-component-call-module] 
[terrahub-component-call-module] An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

[terrahub-component-call-module] Terraform will perform the following actions:

[terrahub-component-call-module] + module.terrahub-project.aws_ssm_parameter.terrahub-component
[terrahub-component-call-module]       id:     <computed>
      arn:    <computed>
[terrahub-component-call-module]       key_id: <computed>
[terrahub-component-call-module]       name:   "terrahub-component_name"
[terrahub-component-call-module]       tier:   "Standard"
      type:   "String"
[terrahub-component-call-module]       value:  <sensitive>
[terrahub-component-call-module] Plan: 1 to add, 0 to change, 0 to destroy.

[terrahub-component-call-module] ------------------------------------------------------------------------

[terrahub-component-call-module] This plan was saved to: /Users/alexandrvozicov/.terrahub/cache/jit/terrahub-component-call-module_0ecd9877/terraform.tfplan

[terrahub-component-call-module] To perform exactly these actions, run the following command to apply:
[terrahub-component-call-module]     terraform apply "/Users/alexandrvozicov/.terrahub/cache/jit/terrahub-component-call-module_0ecd9877/terraform.tfplan"
[terrahub-component-call-module] 
✅ Done
```

aws:
```
## local config
component:
  name: terrahub-component-call-module
  template:
      module:
        terrahub-project:
          source: '../../terrahub-project/terrahub-component'
          terrahub-component_name: ${var.terrahub-component_name}
          terrahub-component_value: terrahub-component_value
          terrahub-component_type: String
terraform:
  varFile: 
    - s3://terrahub-automation-testing/default.tfvars 
 ```

Output:
```
Alexandrs-MacBook-Pro:terrahub-component-call-module alexandrvozicov$ rm -rf ~/.terrahub/cache/*
Alexandrs-MacBook-Pro:terrahub-component-call-module alexandrvozicov$ terrahub run
Project: terrahub-project
 └─ terrahub-component-call-module
💡 'terrahub run' action is executed for above list of components.
💡 [terrahub-component-call-module] terraform init -no-color -force-copy -input=false .
[terrahub-component-call-module] Initializing modules...
[terrahub-component-call-module] - module.terrahub-project
[terrahub-component-call-module]   Getting source "/Users/alexandrvozicov/Projects/scripts/automation/terrahub-project/terrahub-component"
[terrahub-component-call-module] 
[terrahub-component-call-module] Initializing provider plugins...
[terrahub-component-call-module] - Checking for available provider plugins on https://releases.hashicorp.com...
[terrahub-component-call-module] - Downloading plugin for provider "aws" (2.11.0)...
[terrahub-component-call-module] 
[terrahub-component-call-module] The following providers do not have any version constraints in configuration,
so the latest version was installed.

To prevent automatic upgrades to new major versions that may contain breaking
[terrahub-component-call-module] changes, it is recommended to add version = "..." constraints to the
[terrahub-component-call-module] corresponding provider blocks in configuration, with the constraint strings
[terrahub-component-call-module] suggested below.

[terrahub-component-call-module] * provider.aws: version = "~> 2.11"

[terrahub-component-call-module] Terraform has been successfully initialized!

[terrahub-component-call-module] You may now begin working with Terraform. Try running "terraform plan" to see
[terrahub-component-call-module] any changes that are required for your infrastructure. All Terraform commands
[terrahub-component-call-module] should now work.

[terrahub-component-call-module] If you ever set or change modules or backend configuration for Terraform,
[terrahub-component-call-module] rerun this command to reinitialize your working directory. If you forget, other
[terrahub-component-call-module] commands will detect it and remind you to do so if necessary.
💡 [terrahub-component-call-module] terraform workspace list
[terrahub-component-call-module] * default

💡 [terrahub-component-call-module] terraform plan -no-color -var-file='/Users/alexandrvozicov/.terrahub/cache/jit/terrahub-component-call-module_0ecd9877/default.tfvars' -out=/Users/alexandrvozicov/.terrahub/cache/jit/terrahub-component-call-module_0ecd9877/terraform.tfplan -input=false
[terrahub-component-call-module] Refreshing Terraform state in-memory prior to plan...
[terrahub-component-call-module] The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

[terrahub-component-call-module] 
[terrahub-component-call-module] ------------------------------------------------------------------------
[terrahub-component-call-module] 
[terrahub-component-call-module] An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
[terrahub-component-call-module]   + create

[terrahub-component-call-module] Terraform will perform the following actions:
[terrahub-component-call-module] 
[terrahub-component-call-module] + module.terrahub-project.aws_ssm_parameter.terrahub-component
[terrahub-component-call-module]       id:     <computed>
[terrahub-component-call-module]       arn:    <computed>
[terrahub-component-call-module]       key_id: <computed>
[terrahub-component-call-module]       name:   "terrahub-component_name"
      tier:   "Standard"
[terrahub-component-call-module]       type:   "String"
[terrahub-component-call-module]       value:  <sensitive>
[terrahub-component-call-module] Plan: 1 to add, 0 to change, 0 to destroy.
[terrahub-component-call-module] 
[terrahub-component-call-module] ------------------------------------------------------------------------

[terrahub-component-call-module] This plan was saved to: /Users/alexandrvozicov/.terrahub/cache/jit/terrahub-component-call-module_0ecd9877/terraform.tfplan

[terrahub-component-call-module] To perform exactly these actions, run the following command to apply:
[terrahub-component-call-module]     terraform apply "/Users/alexandrvozicov/.terrahub/cache/jit/terrahub-component-call-module_0ecd9877/terraform.tfplan"
[terrahub-component-call-module] 
✅ Done
Alexandrs-MacBook-Pro:terrahub-component-call-module alexandrvozicov$ 
```
