### ISSUE TITLE
TerraHub CLI fails to generate corresponding definition in variable.tf file associated with tfvars config

### ISSUE THREAD

**Issue by eistrati** [TerraHubCorp/terrahub#702]
# Bug Report

## Describe the Bug
TerraHub CLI fails to generate corresponding definition in variable.tf file associated with tfvars config

## To Reproduce
1. Setup at least 1 variable in root .terrahub.yml:
```
[...]
template:
  variable:
    provider_region:
      default: 'us-east-1'
```
2. Setup at least 1 tfvars in component .terrahub.yml:
```
component:
  name: CrossAccountRoleForThub
  template:
    tfvars:
      role_name: 'CrossAccountRoleForThub'
[...]
```
3. Execute terrahub init:
```
$ terrahub init -i CrossAccountRoleForThub
Project: Security_Terraform
 └─ CrossAccountRoleForThub
💡 'terrahub init' action is executed for above list of components.
💡 [CrossAccountRoleForThub] terraform init -no-color -force-copy -input=false .
[CrossAccountRoleForThub] 
[CrossAccountRoleForThub] Initializing the backend...
[CrossAccountRoleForThub] 
[CrossAccountRoleForThub] Successfully configured the backend "s3"! Terraform will automatically
[CrossAccountRoleForThub] use this backend unless the backend configuration changes.

❌ [CrossAccountRoleForThub] Error: resource 'aws_iam_role.cross_account_role_thub_account_01' config: unknown variable referenced: 'role_name'; define it with a 'variable' block
```

**Comment by avozicov** [comment]
Implemented.
- requires to be release in alpha 


Project root .yml:
```
## project config
project:
  name: 'terrahub-project'
  code: '0ecd9877'
  include:
    - '.'
  exclude:
    - '**/.terraform/**'
    - '**/node_modules/**'
    - '**/.git/**'

## terraform config
terraform:
  varFile:
    - 'default.tfvars'
template:
  provider:
    aws: 
      region: ${var.provider_region}
  variable:
    provider_region:
      default: 'us-east-1'
```

component .yml:
```
## local config
component:
  name: terrahub-component-call-module
  template:
      module:
        terrahub-project:
          source: '../../terrahub-project/terrahub-component'
          terrahub-component_name: ${var.terrahub-component_name}
          terrahub-component_value: terrahub-component_value
          terrahub-component_type: String 
      tfvars:
        provider_region: 'us-east-1'
        terrahub-component_name: terrahub-component_name
```

Output from terrahub init -i component_name :
```
Alexandrs-MacBook-Pro:terrahub-component-call-module alexandrvozicov$ ls -la ~/.terrahub/cache/jit/terrahub-component-call-module_0ecd9877/
total 48
drwxr-xr-x   7 alexandrvozicov  staff   224 May 23 13:36 .
drwxr-xr-x  14 alexandrvozicov  staff   448 May 23 13:32 ..
drwxr-xr-x   4 alexandrvozicov  staff   128 May 23 13:32 .terraform
-rw-r--r--   1 alexandrvozicov  staff   408 May 23 13:35 locals.tf
-rw-r--r--   1 alexandrvozicov  staff   324 May 23 13:35 module.tf
-rw-r--r--   1 alexandrvozicov  staff    71 May 23 13:35 provider.tf
-rw-r--r--   1 alexandrvozicov  staff  8890 May 23 13:36 terraform.tfplan
Alexandrs-MacBook-Pro:terrahub-component-call-module alexandrvozicov$ terrahub init -i terrahub-component-call-module
Project: terrahub-project
 └─ terrahub-component-call-module
💡 'terrahub init' action is executed for above list of components.
💡 [terrahub-component-call-module] terraform init -no-color -force-copy -input=false .
[terrahub-component-call-module] Initializing modules...
[terrahub-component-call-module] - module.terrahub-project
[terrahub-component-call-module] 
[terrahub-component-call-module] Initializing provider plugins...
[terrahub-component-call-module] 
[terrahub-component-call-module] The following providers do not have any version constraints in configuration,
[terrahub-component-call-module] so the latest version was installed.

[terrahub-component-call-module] To prevent automatic upgrades to new major versions that may contain breaking
[terrahub-component-call-module] changes, it is recommended to add version = "..." constraints to the
[terrahub-component-call-module] corresponding provider blocks in configuration, with the constraint strings
[terrahub-component-call-module] suggested below.

[terrahub-component-call-module] * provider.aws: version = "~> 2.11"

[terrahub-component-call-module] Terraform has been successfully initialized!
[terrahub-component-call-module] 
[terrahub-component-call-module] You may now begin working with Terraform. Try running "terraform plan" to see
[terrahub-component-call-module] any changes that are required for your infrastructure. All Terraform commands
[terrahub-component-call-module] should now work.

[terrahub-component-call-module] If you ever set or change modules or backend configuration for Terraform,
[terrahub-component-call-module] rerun this command to reinitialize your working directory. If you forget, other
[terrahub-component-call-module] commands will detect it and remind you to do so if necessary.
✅ Done
Alexandrs-MacBook-Pro:terrahub-component-call-module alexandrvozicov$ ls -la ~/.terrahub/cache/jit/terrahub-component-call-module_0ecd9877/
total 64
drwxr-xr-x  10 alexandrvozicov  staff   320 May 23 13:51 .
drwxr-xr-x  14 alexandrvozicov  staff   448 May 23 13:32 ..
lrwxr-xr-x   1 alexandrvozicov  staff   105 May 23 13:51 .backup -> /Users/alexandrvozicov/Projects/scripts/automation/terrahub-module/terrahub-component-call-module/.backup
drwxr-xr-x   4 alexandrvozicov  staff   128 May 23 13:32 .terraform
-rw-r--r--   1 alexandrvozicov  staff    93 May 23 13:51 default.tfvars
-rw-r--r--   1 alexandrvozicov  staff   408 May 23 13:51 locals.tf
-rw-r--r--   1 alexandrvozicov  staff   331 May 23 13:51 module.tf
-rw-r--r--   1 alexandrvozicov  staff    84 May 23 13:51 provider.tf
-rw-r--r--   1 alexandrvozicov  staff  8890 May 23 13:36 terraform.tfplan
-rw-r--r--   1 alexandrvozicov  staff   141 May 23 13:51 variable.tf
Alexandrs-MacBook-Pro:terrahub-component-call-module alexandrvozicov$ cat  ~/.terrahub/cache/jit/terrahub-component-call-module_0ecd9877/variable.tf 
{
  "variable": {
    "provider_region": {
      "type": "string"
    },
    "terrahub-component_name": {
      "type": "string"
    }
  }
}
Alexandrs-MacBook-Pro:terrahub-component-call-module alexandrvozicov$ 
```
