### ISSUE TITLE
Apply error from local machine

### ISSUE THREAD

**Issue by euliancom** [TerraHubCorp/terrahub#72]
`terrahub init` - is ok 
```
./terrahub init -i steam-non-prod                                                                            
💡  [steam-non-prod] terraform init -no-color .
[steam-non-prod]Initializing modules...
[steam-non-prod]- module.us-west-2_steam 
...
✅  Done 
```
`terrahub plan` - is ok
```
./terrahub plan -i steam-non-prod                                                                            
💡  [steam-non-prod] terraform plan -no-color -out=/mnt/c/Terraform/migration-terraform/shared_services_vpc/scratch/infra/steam-non-prod/.resource/terraform.tfplan -var-file=/mnt/c/Terraform/migration-terraform/shared_services_vpc/scratch/infra/steam-non-prod/scratch.tfvars
 [steam-non-prod]Acquiring state lock. This may take a few moments...                                                                                                    [steam-non-prod]
...
✅  Done 
```
`terrahub apply` - is wrong
```
./terrahub apply -i steam-non-prod
💡  [steam-non-prod] terraform apply -no-color -auto-approve=true
[steam-non-prod]Acquiring state lock. This may take a few moments...
[steam-non-prod]var.account_id
```     

the settings I used were:
1. remote `tfstate`
2. global `.terrahub.yml` 
```
project:
  name: 'steam'
  code: '340f086a'
  provider: 'aws'

steam-non-prod:
  name: 'steam-non-prod'
  root: './shared_services_vpc/scratch/infra/steam-non-prod/'

  terraform:
    version: 0.11.7
    varFiles:
      - scratch.tfvars
```
