### ISSUE TITLE
`dependsOn` option failed with brew upgrade

### ISSUE THREAD

**Issue by chenrui333** [TerraHubCorp/terrahub#721]
There is some issue when doing brew upgrade: https://github.com/Homebrew/homebrew-core/pull/39628

`.terrahub.yml` template:
```
      project:
        name: terrahub-demo
        code: abcd1234
      vpc_component:
        name: vpc
        root: ./vpc
      subnet_component:
        name: subnet
        root: ./subnet
        dependsOn:
          - ./vpc
```

error:
```
==> /usr/local/Cellar/terrahub/0.2.54/bin/terrahub graph
❌ Couldn't find dependency 'vpc'
Error: terrahub: failed
```
