### ISSUE TITLE
Refactor terraform/backend/local to use terrahub component local instead of path

### ISSUE THREAD

**Issue by euliancom** [TerraHubCorp/terrahub#753]
# Feature Report
Refactor terraform/backend/local to use terrahub component local instead of path

## Describe the Feature

Refactor terraform/backend/local to use terrahub component local instead of path

## Expected Behavior

Current syntax for local backend (notice the relative path):
```
component:
  template:
    terraform:
      backend:
        local:
          path: /tmp/.terrahub/[project_name]/[component_name]/[env]/terraform.tfstate
```

Future syntax for local backend (notice terrahub component local):
```
component:
  template:
    terraform:
      backend:
        local:
          path: ${local.component["local"]}/[component_name]/[env]/terraform.tfstate
```

Current syntax for remote s3 backend (notice the relative path):
```
component:
  template:
    terraform:
      backend:
        remote:
          s3:
            key: [project_name]/[component_name]/[env]/terraform.tfstate
```

Future syntax for remote s3 backend (notice terrahub component local):
```
component:
  template:
    terraform:
      backend:
        remote:
          s3:
            key: ${local.component["remote"]}/[component_name]/[env]/terraform.tfstate
```
