### ISSUE TITLE
Passing --var-file through cli doesn't generate missing variables in variable.tf for JIT implementation

### ISSUE THREAD

**Issue by eistrati** [TerraHubCorp/terrahub#772]
## Describe the Bug

Passing --var-file through cli doesn't generate missing variables in variable.tf for JIT implementation

## To Reproduce

Define in root `.terrahub.yml`:
```
template:
  tfvars:
    account_id: 123456789012
    region: us-east-1
```

Make sure that component `.terrahub.yml` has no definition for `template.tfvars` and execute `terrahub run` with `--var-file` option:
```
terrahub run --include s3_bucket --var-file ../path/to/external/default.tfvars
```

## Expected Behavior

There should be no errors. Instead, we have seen errors that some variables are not defined.
