### ISSUE TITLE
Error: Provider "aws" depends on non-var "local.region"

### ISSUE THREAD

**Issue by eistrati** [TerraHubCorp/terrahub#774]
## Describe the Bug

Error: Provider "aws" depends on non-var "local.region"

## To Reproduce

Here is my root `.terrahub.yml`:
```
template:
  locals:
    region: us-east-1
    account_id: 123456789012
  provider:
    aws:
      region: ${local.region}
      allowed_account_ids:
        - ${local.account_id}
```

Here is my component `.terrahub.yml`:
```
component:
  name: api_gateway_domain_name
  template:
    resource:
      aws_api_gateway_domain_name:
        api_gateway_domain_name:
          domain_name: ${var.api_gateway_domain_name}
          endpoint_configuration:
            - types: ${var.api_gateway_domain_name_endpoint_type}
          regional_certificate_arn: arn:aws:acm:${local.region}:${local.account_id}:certificate/${var.api_gateway_domain_name_certificate_id}
```

I ran the following command:
```
terrahub import -i api_gateway_domain_name -c 'aws_api_gateway_domain_name.api_gateway_domain_name=api.mydomain.com'
```

## Expected Behavior

I was expecting no issues, but received the following error:
```
❌ [api_gateway_domain_name] Error: Provider "aws" depends on non-var "local.region". Providers for import can currently
only depend on variables or must be hardcoded. You can stop import
from loading configurations by specifying `-config=""`.



{ ChildProcessError: 
Error: Provider "aws" depends on non-var "local.region". Providers for import can currently
only depend on variables or must be hardcoded. You can stop import
from loading configurations by specifying `-config=""`.



    at ChildProcess.<anonymous> (/Volumes/Data/Users/eugene/Projects/hub/node_modules/child-process-promise/lib/index.js:132:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:891:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
  name: 'ChildProcessError',
  code: 1,
  childProcess: 
   ChildProcess {
     domain: null,
     _events: { error: [Function: t], close: [Function] },
     _eventsCount: 2,
     _maxListeners: undefined,
     _closesNeeded: 3,
     _closesGot: 3,
     connected: false,
     signalCode: null,
     exitCode: 1,
     killed: false,
     spawnfile: '/bin/sh',
     _handle: null,
     spawnargs: 
      [ '/bin/sh',
        '-c',
        '/Volumes/Data/Users/eugene/.terrahub/terraform/0.11.11/terraform import -no-color -var-file=\'/Volumes/Data/Users/eugene/.terrahub/cache/jit/api_gateway_domain_name_807a087b/default.tfvars\' -input=false aws_api_gateway_domain_name.api_gateway_domain_name api.mydomain.com' ],
     pid: 96269,
     stdin: 
      Socket {
        connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: null,
        _readableState: [Object],
        readable: false,
        domain: null,
        _events: [Object],
        _eventsCount: 2,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        destroyed: true,
        _bytesDispatched: 0,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        write: [Function: writeAfterFIN],
        _idleNext: null,
        _idlePrev: null,
        _idleTimeout: -1 },
     stdout: 
      Socket {
        connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: null,
        _readableState: [Object],
        readable: false,
        domain: null,
        _events: [Object],
        _eventsCount: 4,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        destroyed: true,
        _bytesDispatched: 0,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        read: [Function],
        _consuming: true,
        _idleNext: null,
        _idlePrev: null,
        _idleTimeout: -1,
        write: [Function: writeAfterFIN] },
     stderr: 
      Socket {
        connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: null,
        _readableState: [Object],
        readable: false,
        domain: null,
        _events: [Object],
        _eventsCount: 4,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        destroyed: true,
        _bytesDispatched: 0,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        read: [Function],
        _consuming: true,
        _idleNext: null,
        _idlePrev: null,
        _idleTimeout: -1,
        write: [Function: writeAfterFIN] },
     stdio: [ [Object], [Object], [Object] ] },
  stdout: undefined,
  stderr: undefined }
❌ Worker error: "Cannot set property 'action' of undefined"
```

**Comment by euliancom** [comment]
I have opened a ticket to `Hashicorp` - https://github.com/hashicorp/terraform/issues/20890.

**Comment by eistrati** [comment]
While terraform is solving this issue, we recommend using `tfvars` instead of `locals`. For above described example, we should use the following approach:

```
template:
  tfvars:
    region: us-east-1
    account_id: 123456789012
  provider:
    aws:
      region: ${var.region}
      allowed_account_ids:
        - ${var.account_id}
```
