### ISSUE TITLE
Refactor terrahub cli to use terraform v0.12+

### ISSUE THREAD

**Issue by eistrati** [TerraHubCorp/terrahub#810]
## Describe the Feature

Refactor terrahub cli to use terraform v0.12+

**Comment by euliancom** [comment]
Steps:
1. Change the default version of terraform from v.0.11.11 to v.0.12.3
2. Change the extension of files generated by jit class.
3. Edit `.terrahub.yml.twig`
4. Add check step for verifying the terraform version in jit class 
5. Divide the jit class in 2 (one for v.0.12 and the other for v.0.11)
6. Fix the third application for template generate (GoLang)
7. Generate all templates for v.0.12
8. Fix the template mapping to use v.0.12 by default and v.0.11 if in root config is specified this version
9. Fix the third application form conversion (GoLang, add convert to hcl2)
10. Fix the class for conversion in terrahub (add convert to hcl2)

**Comment by const-andreyLu** [comment]
terrahub.yml: 
```
component:
  name: terrahub_load_outputs
  template:
    terraform:
      backend:
        local:
          path: >-
            ${tfvar.terrahub["tfstate_path"]}/terrahub_load_outputs/terraform.tfstate
    output:
      terrahub_reader:
        value: >-
          merge(map("ids",data.terraform_remote_state.landing_zone_security_group.ids,"landing_zone_security_group_ids",data.terraform_remote_state.landing_zone_security_group.landing_zone_security_group_ids,"thub_ids",data.terraform_remote_state.landing_zone_security_group.thub_ids),map("arns",data.terraform_remote_state.landing_zone_subnet.arns,"availability_zone_ids",data.terraform_remote_state.landing_zone_subnet.availability_zone_ids,"ids",data.terraform_remote_state.landing_zone_subnet.ids,"landing_zone_subnet_arns",data.terraform_remote_state.landing_zone_subnet.landing_zone_subnet_arns,"landing_zone_subnet_availability_zone_ids",data.terraform_remote_state.landing_zone_subnet.landing_zone_subnet_availability_zone_ids,"landing_zone_subnet_ids",data.terraform_remote_state.landing_zone_subnet.landing_zone_subnet_ids,"thub_ids",data.terraform_remote_state.landing_zone_subnet.thub_ids),map("arns",data.terraform_remote_state.landing_zone_vpc.arns,"ids",data.terraform_remote_state.landing_zone_vpc.ids,"landing_zone_vpc_arns",data.terraform_remote_state.landing_zone_vpc.landing_zone_vpc_arns,"landing_zone_vpc_ids",data.terraform_remote_state.landing_zone_vpc.landing_zone_vpc_ids,"thub_ids",data.terraform_remote_state.landing_zone_vpc.thub_ids))
    data:
      terraform_remote_state:
        landing_zone_security_group:
          backend: local
          config:
            path: >-
              ${tfvar.terrahub["tfstate_path"]}/landing_zone_security_group/terraform.tfstate
        landing_zone_subnet:
          backend: local
          config:
            path: >-
              ${tfvar.terrahub["tfstate_path"]}/landing_zone_subnet/terraform.tfstate
        landing_zone_vpc:
          backend: local
          config:
            path: >-
              ${tfvar.terrahub["tfstate_path"]}/landing_zone_vpc/terraform.tfstate

```

output : 
```
➜ terrahub run -i terrahub_load_outputs
💡 THUB_TOKEN is not provided.
Project: terraform-aws-landing-zone
 └─ terrahub_load_outputs
💡 'terrahub run' action is executed for above list of components.
💡 [terrahub_load_outputs] terraform init -no-color -force-copy -input=false .
[terrahub_load_outputs] 
Initializing the backend...
[terrahub_load_outputs] 
Initializing provider plugins...
[terrahub_load_outputs] 
[terrahub_load_outputs] The following providers do not have any version constraints in configuration,
so the latest version was installed.

To prevent automatic upgrades to new major versions that may contain breaking
[terrahub_load_outputs] changes, it is recommended to add version = "..." constraints to the
[terrahub_load_outputs] corresponding provider blocks in configuration, with the constraint strings
suggested below.

* provider.aws: version = "~> 2.20"

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.
[terrahub_load_outputs] 
[terrahub_load_outputs] If you ever set or change modules or backend configuration for Terraform,
[terrahub_load_outputs] rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
💡 [terrahub_load_outputs] terraform workspace list
[terrahub_load_outputs] * default

💡 [terrahub_load_outputs] terraform plan -no-color -var-file='/Users/andreyluchianic/.terrahub/cache/jit/terrahub_load_outputs_eef16dcf/default.tfvars' -out=/Users/andreyluchianic/.terrahub/cache/jit/terrahub_load_outputs_eef16dcf/terraform.tfplan -input=false
❌ [terrahub_load_outputs] Error: Reference to undeclared local value

  on  line 0:

❌ [terrahub_load_outputs]   (source code not available)

A local value with the name "" has not been declared.


❌ [terrahub_load_outputs] Error: Reference to undeclared local value

  on  line 0:

❌ [terrahub_load_outputs]   (source code not available)

A local value with the name "" has not been declared.


Error: Reference to undeclared local value

❌ [terrahub_load_outputs] 
  on  line 0:

❌ [terrahub_load_outputs]   (source code not available)


❌ [terrahub_load_outputs] A local value with the name "" has not been declared.


❌ [terrahub_load_outputs] 
Error: Invalid reference


❌ [terrahub_load_outputs]   on data.tf line 2, in data "terraform_remote_state" "landing_zone_security_group":

❌ [terrahub_load_outputs]    2:   backend = local


❌ [terrahub_load_outputs] The "local" object cannot be accessed directly. Instead, access one of its
attributes.


❌ [terrahub_load_outputs] 
Error: Invalid reference


❌ [terrahub_load_outputs]   on data.tf line 8, in data "terraform_remote_state" "landing_zone_subnet":

❌ [terrahub_load_outputs]    8:   backend = local


❌ [terrahub_load_outputs] The "local" object cannot be accessed directly. Instead, access one of its
attributes.

❌ [terrahub_load_outputs] 
Error: Invalid reference

❌ [terrahub_load_outputs]   on data.tf line 14, in data "terraform_remote_state" "landing_zone_vpc":
  14:   backend = local

❌ [terrahub_load_outputs] 
The "local" object cannot be accessed directly. Instead, access one of its
attributes.


❌ Worker error: Error: Reference to undeclared local value

  on  line 0:
  (source code not available)

A local value with the name "" has not been declared.


Error: Reference to undeclared local value

  on  line 0:
  (source code not available)

A local value with the name "" has not been declared.


Error: Reference to undeclared local value

  on  line 0:
  (source code not available)

A local value with the name "" has not been declared.


Error: Invalid reference

  on data.tf line 2, in data "terraform_remote_state" "landing_zone_security_group":
   2:   backend = local

The "local" object cannot be accessed directly. Instead, access one of its
attributes.


Error: Invalid reference

  on data.tf line 8, in data "terraform_remote_state" "landing_zone_subnet":
   8:   backend = local

The "local" object cannot be accessed directly. Instead, access one of its
attributes.

Error: Invalid reference
  on data.tf line 14, in data "terraform_remote_state" "landing_zone_vpc":
  14:   backend = local

The "local" object cannot be accessed directly. Instead, access one of its
attributes.


```
