### ISSUE TITLE
Enable partial configuration for terraform backend-config

### ISSUE THREAD

**Issue by eistrati** [TerraHubCorp/terrahub#86]
We tried with @euliancom  to programmatically overwrite backend config values and got the following error:

```
Error loading backend config: 1 error(s) occurred:

* terraform.backend: configuration cannot contain interpolations

The backend configuration is loaded by Terraform extremely early, before
the core of Terraform can be initialized. This is necessary because the backend
dictates the behavior of that core. The core is what handles interpolation
processing. Because of this, interpolations cannot be used in backend
configuration.

If you'd like to parameterize backend configuration, we recommend using
partial configuration with the "-backend-config" flag to "terraform init".
```

In order to fix this issue, we need to run `terraform init -backend-config="KEY=VALUE"` (see https://www.terraform.io/docs/backends/config.html#partial-configuration). Let's implement this feature using `.terrahub.yml` configuration as follows:
```
terraform:
  backend:
    region: us-east-1
    bucket: data-lake-terrahub-us-east-1
    key: path/to/terraform.tfstate
    encrypt: false
```
