### ISSUE TITLE
Automatically define `terraform_remote_state` data when using `dependsOn` statement

### ISSUE THREAD

**Issue by eistrati** [TerraHubCorp/terrahub#860]
## Describe the Feature
Automatically define `terraform_remote_state` data when using `dependsOn` statement

## Expected Behavior
Current configuration syntax and cli behavior:
```yml
component:
  name: landing_zone_cloudtrail
  dependsOn:
    - ../landing_zone_cloudtrail_s3_bucket
  template:
    data:
      terraform_remote_state:
        landing_zone_cloudtrail_s3_bucket:
          backend: local
          config:
            path: >-
              ${tfvar.terrahub["tfstate_path"]}/landing_zone_cloudtrail_s3_bucket/terraform.tfstate
```

Future configuration syntax and exactly the same cli behavior:
```yml
component:
  name: landing_zone_cloudtrail
  dependsOn:
    - landing_zone_cloudtrail_s3_bucket
```

> NOTE: Depends on https://github.com/TerraHubCorp/terrahub/issues/744

**Comment by eistrati** [comment]
After a quick conversation, we agreed on the following syntax:
```yml
component:
  name: landing_zone_cloudtrail
  dependsOn:
    - landing_zone_cloudtrail_s3_bucket
    - landing_zone_cloudtrail_kms_key
  template:
    dynamic:
      data:
        terraform_remote_state:
          - component: landing_zone_cloudtrail_s3_bucket
            name: s3_bucket_${tfvars.terrahub["default"][0]}
            provider: ${tfvars.terrahub["default"][0]}
```

**Comment by eistrati** [comment]
Use case when defining all components, let's use the following syntax:
```yml
component:
  name: landing_zone_cloudtrail
  dependsOn:
    - landing_zone_cloudtrail_s3_bucket
    - landing_zone_cloudtrail_kms_key
  template:
    dynamic:
      data:
        terraform_remote_state:
          - component: *    ## or any other regexp
             name: prefix_*    ## or any other regexp
```
