### ISSUE TITLE
Parse `local.*` inside `tfvar.*` definitions and vice-versa

### ISSUE THREAD

**Issue by eistrati** [TerraHubCorp/terrahub#861]
## Describe the Feature
Parse `local.*` inside `tfvar.*` definitions and vice-versa

## Expected Behavior
```yml
component:
  name: landing_zone_cloudtrail
  dependsOn:
    - landing_zone_cloudtrail_s3_bucket
  template:
    terraform:
      backend:
        local:
          path: >-
            ${tfvar.terrahub["root_path"]}/${local.terrahub["component_name"]}/terraform.tfstate
    tfvars:
      root_path: ${local.terrahub["root_path"]}
    local:
      component_name: ${tfvars.terrahub["component_name"]}
```

P. S. Above example doesn't entirely make sense, but the purpose of it is primarily to enhance the capability of terrahub cli to parse successfully both `local.*` and `tfvar.*` in the same execution
