### ISSUE TITLE
Update `convert` command

### ISSUE THREAD

**Issue by aluchianic** [TerraHubCorp/terrahub#876]
# Bug Report

## Describe the Bug

When terrahub run -- apply -i  landing_zone_pipeline_s3_bucket getting error :

❌ [landing_zone_pipeline_s3_bucket] Error: Unsupported argument
❌ [landing_zone_pipeline_s3_bucket] {
An argument named "versioning" is not expected here. Did you mean to define a
block of type "versioning"?
}

default.tfvars : 
 ```
landing_zone_providers = [
  "default"
]

landing_zone_pipeline_s3_bucket_name = "aws-landing-zone-configuration"

landing_zone_pipeline_s3_bucket_versioning = true

```

## To Reproduce

1. Go to aws_landing_zone
2. use tfvars locally 
3. start local execution

**Comment by vcalmic** [comment]
Got this issue when deploying a lambda function using terraform 0.12
```
## local config
component:
  name: lambda
  template:
    resource:
      aws_lambda_function:
        lambda:
          handler: "index.handler"
          runtime: nodejs10.x
          role: rolename
          function_name: lambda_function_name
```
```
💡 [lambda] terraform plan -no-color -out=/home/vcalmic/.terrahub/cache/hcl/lambda_f79f9b12/terraform.tfplan -input=false
❌ [lambda] 
Error: Reference to undeclared resource

  on main.tf line 4, in resource "aws_lambda_function" "lambda":
   4:   handler       = index.handler


❌ [lambda] A managed resource "index" "handler" has not been declared in the root module.


❌ Worker error: 
Error: Reference to undeclared resource

  on main.tf line 4, in resource "aws_lambda_function" "lambda":
   4:   handler       = index.handler

A managed resource "index" "handler" has not been declared in the root module.
```
```
resource "aws_lambda_function" "lambda" {
  role          = "ServiceRoleForLambdaEdge"
  function_name = "lambda_function_name"
  handler       = index.handler
  runtime       = "nodejs10.x"
}
```
