### ISSUE TITLE
Unable to configure a workspace environment of a component if another one dependsOn it

### ISSUE THREAD

**Issue by mnegura** [TerraHubCorp/terrahub#891]
# Bug Report

## Describe the Bug
Unable to configure a workspace environment of a component if another one dependsOn it

## To Reproduce

1. Create `thub project`
2. Create and `s3_bucket`
3. Create an `lambda_function` that `dependsOn` our s3_bucket
4. `terrahub workspace --env 'workspace_name' -i s3_bucket`
5. `terrahub configure --config component.template={} -i s3_bucket --env workspace_name -p ignore`
See the error

## Expected Behavior

No errors and a successful configuration

## Error Output

```
➜ thub configure --config component.template={} -i s3_bucket --env workspace_name -p ignore           
💡 THUB_TOKEN is not provided.
❌ TerraHub failed because of the following issues:
1. 'lambda_function' component depends on the component 's3_bucket' that either are not included or do not exist
```

## Desktop

 - OS: macOS
 - Version: v0.3.15

**Comment by aluchianic** [comment]
I tried to reproduce this error (in `dev` branch). My components
```yml
component:
  name: s3_bucket
  template:
    terraform:
      backend:
        s3:
          key: terraform/ssm_parameter/2-tester/terraform.tfstate
          bucket: data-lake-terrahub-us-east-1
          region: us-east-1
    resource:
      aws_s3_bucket:
        s3_bucket:
           bucket: 'aluchianic-2-test-bucket'
```
```yml
component:
  name: lambda_function
  dependsOn:
    - s3_bucket
  template:
    resource:
      aws_lambda_function:
        lambda_function:
          handler: var.lambda_function_handler
          runtime: var.lambda_function_runtime
          role: var.lambda_function_role
          function_name: var.lambda_function_function_name
```

 got this output : 
```
➜ thub project -n clear-project -d clear-project          
💡 THUB_TOKEN is not provided.
✅ Project successfully initialized

➜ thub component -n lambda_function -t aws_lambda_function
💡 THUB_TOKEN is not provided.
✅ Done

➜ thub component -n s3_bucket -t aws_s3_bucket            
💡 THUB_TOKEN is not provided.
✅ Done

➜ terrahub workspace --env 'MY_TEST_WORKSPACE' -i s3_bucket
💡 THUB_TOKEN is not provided.
Project: clear-project
 └─ s3_bucket
💡 'terrahub workspace' action is executed for above list of components.
💡 [s3_bucket] terraform init -no-color -force-copy -input=false .
[s3_bucket] 
[s3_bucket] Initializing the backend...
[s3_bucket] 
Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.
[s3_bucket] 
Initializing provider plugins...
[s3_bucket] - Checking for available provider plugins...
[s3_bucket] - Downloading plugin for provider "aws" (hashicorp/aws) 2.33.0...
[s3_bucket] 
[s3_bucket] The following providers do not have any version constraints in configuration,
so the latest version was installed.

To prevent automatic upgrades to new major versions that may contain breaking
changes, it is recommended to add version = "..." constraints to the
corresponding provider blocks in configuration, with the constraint strings
[s3_bucket] suggested below.

[s3_bucket] * provider.aws: version = "~> 2.33"

Terraform has been successfully initialized!

[s3_bucket] You may now begin working with Terraform. Try running "terraform plan" to see
[s3_bucket] any changes that are required for your infrastructure. All Terraform commands
[s3_bucket] should now work.

[s3_bucket] If you ever set or change modules or backend configuration for Terraform,
[s3_bucket] rerun this command to reinitialize your working directory. If you forget, other
[s3_bucket] commands will detect it and remind you to do so if necessary.
💡 [s3_bucket] terraform workspace list
[s3_bucket] * default
[s3_bucket] 
✅ TerraHub environment 'MY_TEST_WORKSPACE' was created

➜ thub configure --config component.template={} -i s3_bucket --env MY_TEST_WORKSPACE -p ignore 
💡 THUB_TOKEN is not provided.
✅ Done

```
I think problem was in dependsOn names.
