### ISSUE TITLE
Create native support for sentinel as part of `terrahub run` workflow

### ISSUE THREAD

**Issue by eistrati** [TerraHubCorp/terrahub#986]
## Describe the Feature
Create native support for sentinel as part of `terrahub run` workflow

## Expected Behavior
Based on customers feedback, please add native support for sentinel. We propose the following syntax structure in configuration:
```yml
hook:
  plan:
    sentinel:
      path: [ plan.sentinel ]
      version: 0.14.2
  apply:
    sentinel:
      path: [ plan.sentinel, apply.sentinel ]
      version: 0.14.1
  destroy:
    sentinel:
      path: [ destroy.sentinel ]
      version: 0.14.0
```
